import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import TopHeader from '../components/Header';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Booklog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap"
            rel="stylesheet"
          ></link>
        </Head>

        <main className={styles.main}>
          <Link href="/dashboard">
            <a>Dashboard</a>
          </Link>
        </main>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </div>
    </>
  );
}
