import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAuth } from '../components/AuthProvider/auth-provider';
import LandingPage from '../pages/landing-page/index';

export default function Home() {
  const { session } = useAuth();

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Booklog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          {session?.user?.email && (
            <h2>
              Vítej, <span className="username">{session?.user?.email}</span>{' '}
            </h2>
          )}
          <LandingPage />
        </div>
      </div>
    </>
  );
}
