import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import TopHeader from '../components/Header/header';
import Layout from '../components/Layout/layout';
import BookCard from '../components/BookCard/book-card';
import styles from '../styles/Home.module.css';
import { useAuth } from '../components/AuthProvider/auth-provider';
import LandingPage from '../pages/landing-page/index';

export default function Home() {
  const { session } = useAuth();

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Booklog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <h2>Vítej {session?.user?.email}</h2>
          <LandingPage />
        </div>
      </div>
    </>
  );
}
